
//! Autogenerated weights for `pallet_encointer_reputation_commitments`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-08, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Fabian-iPhone.localdomain`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/encointer-node-notee
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_encointer_reputation_commitments
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=runtime/src/weights/pallet_encointer_reputation_commitments.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_encointer_reputation_commitments`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_encointer_reputation_commitments::WeightInfo for WeightInfo<T> {
	// Storage: EncointerReputationCommitments CurrentPurposeId (r:1 w:1)
	// Storage: EncointerReputationCommitments Purposes (r:0 w:1)
	fn register_purpose() -> Weight {
		// Minimum execution time: 51_000 nanoseconds.
		Weight::from_parts(54_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	// Storage: EncointerReputationCommitments Purposes (r:1 w:0)
	// Storage: EncointerCeremonies ParticipantReputation (r:1 w:0)
	// Storage: EncointerReputationCommitments Commitments (r:1 w:1)
	fn commit_reputation() -> Weight {
		// Minimum execution time: 74_000 nanoseconds.
		Weight::from_parts(76_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
