
//! Autogenerated weights for `pallet_encointer_reputation_rings`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-14, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/encointer-node-notee
// benchmark
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_encointer_reputation_rings
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=runtime/src/weights/pallet_encointer_reputation_rings.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_encointer_reputation_rings`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_encointer_reputation_rings::WeightInfo for WeightInfo<T> {
	fn register_bandersnatch_key() -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn initiate_rings() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// `n`: number of registered keys scanned during collection.
	fn continue_ring_computation_collect(n: u32) -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(50_000, 0).saturating_mul(n as u64))
			.saturating_add(T::DbWeight::get().reads(2 + n as u64))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// `n`: number of members in the ring being built.
	fn continue_ring_computation_build(n: u32) -> Weight {
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(100_000, 0).saturating_mul(n as u64))
			.saturating_add(T::DbWeight::get().reads(1 + n as u64))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
