name: build and test notee client and node

on:
  workflow_dispatch:
  push:
    branches: [ master, sgx-master ]
  pull_request:
    branches: [ master, sgx-master ]
#  schedule:
#    - cron:  '42 3 * * *'
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: init-rust-target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: executables
        path: | 
          target/release/encointer-node-notee
          target/release/encointer-client-notee

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: init-rust-target
      run: rustup target add wasm32-unknown-unknown
    - name: cargo test
      run: cargo test --all

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: init-rust
      run: rustup component add clippy
    - name: cargo clippy client
      run: cargo clippy -p encointer-client-notee

  test-bootstrapping:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: download build artifacts
      uses: actions/download-artifact@master
    - name: fix permissions of artifacts and move to original folder
      run: |
        chmod +x executables/encointer-node-notee
        chmod +x executables/encointer-client-notee
        mkdir -p target/release
        mv executables/* target/release
    - name: start dev node
      run: 
        ./target/release/encointer-node-notee --tmp --dev &
    - name: get-phase
      run: ./target/release/encointer-client-notee get-phase
    - name: next-phase
      run: ./target/release/encointer-client-notee next-phase
    - name: bootstrap community
      run: |
        cd client
        ./bootstrap_demo_community.sh

  test-community-growing:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - name: download build artifacts
      uses: actions/download-artifact@master
    - name: fix permissions of artifacts and move to original folder
      run: |
        chmod +x executables/encointer-node-notee
        chmod +x executables/encointer-client-notee
        mkdir -p target/release
        mv executables/* target/release
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install py dependencies
      run: |
        python -m pip install --upgrade pip
        pip install geojson pyproj
    - name: start dev node
      run: /home/runner/work/encointer-node/encointer-node/executables/encointer-node-notee --tmp --dev &
    - name: grow community
      run: |
        cd client
        python bot-community.py init
        python bot-community.py run

