name: build node and client

on:
  push:
    branches: [ master, sgx-master ]
  pull_request:
    branches: [ master, sgx-master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: init-rust-target
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: | 
          target/release/encointer-node-*
          target/release/encointer-client-*
          !target/release/*.d

